// AI sanity 測試：找一手勝、擋衝四、迴避禁手、難度分級在時限內回手。
import { describe, it, expect } from 'vitest'
import { parseBoard } from '../testutils.ts'
import { BLACK, idx } from '../types.ts'
import { createBoard } from '../board.ts'
import { isWinningMove } from '../rules.ts'
import { isForbiddenMove } from '../forbidden.ts'
import { generateMoves } from '../movegen.ts'
import { search, LEVELS } from '../search.ts'

describe('走子生成', () => {
  it('空盤回天元', () => {
    const b = createBoard()
    expect(generateMoves(b, BLACK, 'renju', 10)).toEqual([{ x: 7, y: 7, score: 0 }])
  })

  it('renju 黑候選手不含禁手點', () => {
    // (7,7) 是三三禁手（case 16b 同形）
    const { board } = parseBoard(`
      ...............
      ...............
      ...............
      ...............
      ...............
      .......X.......
      .......X.......
      .....XX........
      ...............
      ..O.O.O.O......
    `)
    const moves = generateMoves(board, BLACK, 'renju', 50)
    expect(moves.length).toBeGreaterThan(0)
    expect(moves.some((m) => m.x === 7 && m.y === 7)).toBe(false)
    // gomoku 無禁手 → (7,7) 應在候選中
    const g = generateMoves(board, BLACK, 'gomoku', 50)
    expect(g.some((m) => m.x === 7 && m.y === 7)).toBe(true)
  })
})

describe('AI sanity', () => {
  it('各難度都找到一手勝（黑有活四）且不改盤面', () => {
    const { board } = parseBoard(`
      O.O.O..........
      ...............
      ...............
      ...............
      ...............
      ...............
      ...............
      ....XXXX.......
    `)
    for (const level of [1, 2, 3, 4] as const) {
      const before = [...board]
      const r = search(board, BLACK, { rule: 'renju', ...LEVELS[level] })
      expect([...board]).toEqual(before)
      expect(r.move).not.toBeNull()
      board[idx(r.move!.x, r.move!.y)] = BLACK
      expect(
        isWinningMove(board, r.move!.x, r.move!.y, BLACK, 'renju'),
        `level ${level} 應下成五點，實下 (${r.move!.x},${r.move!.y})`,
      ).toBe(true)
      board[idx(r.move!.x, r.move!.y)] = 0
    }
  }, 30000)

  it('擋對方衝四（唯一成五點必守）', () => {
    const { board } = parseBoard(`
      ...............
      ...............
      ...............
      ...............
      ...............
      ...............
      ...............
      ...XOOOO.......
      ...............
      ...............
      ...............
      ...............
      X.X.X..........
    `)
    const r = search(board, BLACK, { rule: 'renju', ...LEVELS[2] })
    expect(r.move).toEqual({ x: 8, y: 7 })
  }, 10000)

  it('renju 黑的著手永不落禁手點', () => {
    const { board } = parseBoard(`
      ...............
      ...............
      ...............
      ...............
      ...............
      .......X.......
      .......X.......
      .....XX........
      ...............
      ..O.O.O.O......
    `)
    const r = search(board, BLACK, { rule: 'renju', ...LEVELS[1] })
    expect(r.move).not.toBeNull()
    expect(isForbiddenMove(board, r.move!.x, r.move!.y).forbidden).toBe(false)
  }, 10000)

  it('時間限制中斷：限時 600ms 的深搜在寬裕上限內回手', () => {
    const { board } = parseBoard(`
      ...............
      ...............
      ...............
      ...............
      ...............
      ...............
      ...............
      .......XO......
      .......OX......
    `)
    const t0 = Date.now()
    const r = search(board, BLACK, {
      rule: 'gomoku',
      maxDepth: 20,
      timeLimitMs: 600,
      width: 12,
      vcfDepth: 0,
    })
    const elapsed = Date.now() - t0
    expect(r.move).not.toBeNull()
    expect(elapsed).toBeLessThan(3000) // 中斷機制生效（否則 depth 20 會跑到天荒地老）
  }, 10000)

  it('空盤開局下天元', () => {
    const b = createBoard()
    const r = search(b, BLACK, { rule: 'renju', ...LEVELS[1] })
    expect(r.move).toEqual({ x: 7, y: 7 })
  }, 10000)
})
