// AI sanity 測試：找一手勝、擋衝四、迴避禁手、難度分級在時限內回手。
import { describe, it, expect } from 'vitest'
import { parseBoard } from '../testutils.ts'
import { BLACK, WHITE, idx } from '../types.ts'
import { createBoard } from '../board.ts'
import { isWinningMove } from '../rules.ts'
import { isForbiddenMove } from '../forbidden.ts'
import { generateMoves } from '../movegen.ts'
import { search, LEVELS } from '../search.ts'

describe('走子生成', () => {
  it('空盤回天元', () => {
    const b = createBoard()
    expect(generateMoves(b, BLACK, 'renju', 10)).toEqual([{ x: 7, y: 7, score: 0 }])
  })

  it('renju 黑候選手不含禁手點', () => {
    // (7,7) 是三三禁手（case 16b 同形）
    const { board } = parseBoard(`
      ...............
      ...............
      ...............
      ...............
      ...............
      .......X.......
      .......X.......
      .....XX........
      ...............
      ..O.O.O.O......
    `)
    const moves = generateMoves(board, BLACK, 'renju', 50)
    expect(moves.length).toBeGreaterThan(0)
    expect(moves.some((m) => m.x === 7 && m.y === 7)).toBe(false)
    // gomoku 無禁手 → (7,7) 應在候選中
    const g = generateMoves(board, BLACK, 'gomoku', 50)
    expect(g.some((m) => m.x === 7 && m.y === 7)).toBe(true)
  })
})

describe('AI sanity', () => {
  it('各難度都找到一手勝（黑有活四）且不改盤面', () => {
    const { board } = parseBoard(`
      O.O.O..........
      ...............
      ...............
      ...............
      ...............
      ...............
      ...............
      ....XXXX.......
    `)
    for (const level of [1, 2, 3, 4] as const) {
      const before = [...board]
      const r = search(board, BLACK, { rule: 'renju', ...LEVELS[level] })
      expect([...board]).toEqual(before)
      expect(r.move).not.toBeNull()
      board[idx(r.move!.x, r.move!.y)] = BLACK
      expect(
        isWinningMove(board, r.move!.x, r.move!.y, BLACK, 'renju'),
        `level ${level} 應下成五點，實下 (${r.move!.x},${r.move!.y})`,
      ).toBe(true)
      board[idx(r.move!.x, r.move!.y)] = 0
    }
  }, 30000)

  it('擋對方衝四（唯一成五點必守）', () => {
    const { board } = parseBoard(`
      ...............
      ...............
      ...............
      ...............
      ...............
      ...............
      ...............
      ...XOOOO.......
      ...............
      ...............
      ...............
      ...............
      X.X.X..........
    `)
    const r = search(board, BLACK, { rule: 'renju', ...LEVELS[2] })
    expect(r.move).toEqual({ x: 8, y: 7 })
  }, 10000)

  it('renju 黑的著手永不落禁手點', () => {
    const { board } = parseBoard(`
      ...............
      ...............
      ...............
      ...............
      ...............
      .......X.......
      .......X.......
      .....XX........
      ...............
      ..O.O.O.O......
    `)
    const r = search(board, BLACK, { rule: 'renju', ...LEVELS[1] })
    expect(r.move).not.toBeNull()
    expect(isForbiddenMove(board, r.move!.x, r.move!.y).forbidden).toBe(false)
  }, 10000)

  it('時間限制中斷：限時 600ms 的深搜在寬裕上限內回手', () => {
    const { board } = parseBoard(`
      ...............
      ...............
      ...............
      ...............
      ...............
      ...............
      ...............
      .......XO......
      .......OX......
    `)
    const t0 = Date.now()
    const r = search(board, BLACK, {
      rule: 'gomoku',
      maxDepth: 20,
      timeLimitMs: 600,
      width: 12,
      vcfDepth: 0,
    })
    const elapsed = Date.now() - t0
    expect(r.move).not.toBeNull()
    expect(elapsed).toBeLessThan(3000) // 中斷機制生效（否則 depth 20 會跑到天荒地老）
  }, 10000)

  it('空盤開局下天元', () => {
    const b = createBoard()
    const r = search(b, BLACK, { rule: 'renju', ...LEVELS[1] })
    expect(r.move).toEqual({ x: 7, y: 7 })
  }, 10000)
})

describe('衝四紀律（國手回饋：不亂衝四）', () => {
  // 黑唯一的成四點是 (6,3)：OXXX. 衝四後白擋 (7,3) 該線即死、毫無後續；
  // 好手是右下發展（黑有 (8,8)(9,8) 活二、白有活二需要牽制）。
  // 黑無 VCF（引擎驗算過）。修正前的引擎在固定深度 4 會選 (6,3)（horizon
  // effect：衝四交換把局面推出視野）；forced-reply extension 後任一深度
  // （1~6 逐一驗算）都不選。
  const POINTLESS_CHONG = `
    ...............
    ...............
    ...............
    ..OXXX.........
    ...............
    ...............
    ...............
    ...............
    ........XX.....
    ......OO.......
    ...............
  `

  it('L3/L4 不選無意義衝四', () => {
    const { board } = parseBoard(POINTLESS_CHONG)
    for (const level of [3, 4] as const) {
      const r = search(Uint8Array.from(board), BLACK, { rule: 'gomoku', ...LEVELS[level] })
      expect(r.move, `L${level} 不應衝 (6,3)`).not.toEqual({ x: 6, y: 3 })
    }
  }, 30000)

  it('固定深度 4（修正前引擎會衝四的設定）也不選無意義衝四', () => {
    const { board } = parseBoard(POINTLESS_CHONG)
    const r = search(Uint8Array.from(board), BLACK, {
      rule: 'gomoku',
      maxDepth: 4,
      timeLimitMs: 30000,
      width: 14,
      vcfDepth: 0,
    })
    expect(r.move).not.toEqual({ x: 6, y: 3 })
  }, 40000)

  it('forced extension 開啟後，衝四素材滿盤的局面限時仍準時回手', () => {
    // 雙方各兩條被單邊擋死的眠三（衝四素材）＋活二；無 VCF、無速勝
    // （引擎驗算過），深搜必然跑滿時限 → 驗證延伸不破壞時間中斷。
    const { board } = parseBoard(`
      ...............
      ...............
      OXXX...........
      ...........O...
      ...........O...
      ...........O...
      .....XX....X...
      ...............
      .........X.....
      .........X.....
      .....OO..X.....
      .........O.....
      XOOO...........
      ....X..........
      ...............
    `)
    for (const color of [BLACK, WHITE] as const) {
      const t0 = Date.now()
      const r = search(Uint8Array.from(board), color, {
        rule: 'gomoku',
        maxDepth: 20,
        timeLimitMs: 600,
        width: 14,
        vcfDepth: 0,
      })
      const elapsed = Date.now() - t0
      expect(r.move).not.toBeNull()
      expect(elapsed).toBeLessThan(3000)
    }
  }, 10000)
})
