// VCF 搜索器測試：手工構造的簡單 VCF 局、禁手迴避、逼禁手勝、無解局面。
import { describe, it, expect } from 'vitest'
import { parseBoard } from '../testutils.ts'
import { BLACK, WHITE } from '../types.ts'
import { solveVcf } from '../vcf.ts'
import { isWinningMove } from '../rules.ts'
import { idx } from '../types.ts'

describe('VCF solver', () => {
  it('已有活四缺口：一手成五（VCF 長度 1）', () => {
    const { board } = parseBoard(`
      O.O.O..........
      ...............
      ...............
      ...............
      ...............
      ...............
      ...............
      ....XXXX.......
    `)
    const before = [...board]
    const r = solveVcf(board, BLACK, 'renju')
    expect(r.found).toBe(true)
    expect(r.line).toHaveLength(1)
    // 主變化最後一手必為成五
    const m = r.line[0]
    board[idx(m.x, m.y)] = BLACK
    expect(isWinningMove(board, m.x, m.y, BLACK, 'renju')).toBe(true)
    board[idx(m.x, m.y)] = 0
    expect([...board]).toEqual(before) // solver 不留副作用
  })

  it('兩步 VCF：衝四逼擋 → 轉直線活四收束', () => {
    // 黑 (5,7)(6,7)(7,7) 橫排（左被 O 擋）＋ (8,5)(8,6) 直排。
    // 主變化：黑(8,7)衝四（唯一成五點 9,7）→ 白被迫擋 (9,7)
    //        → 黑(8,8) 成直線活四 {(8,5)..(8,8)}（兩個恰五點）→ 勝。
    const { board } = parseBoard(`
      ...............
      ...............
      ...............
      ...............
      ...............
      ........X......
      ........X......
      ....OXXX.......
    `)
    // 收束手 (8,4) 與 (8,8) 皆成活四，是等價主變化，兩者皆接受。
    const r = solveVcf(board, BLACK, 'renju')
    expect(r.found).toBe(true)
    expect(r.line.slice(0, 2)).toEqual([
      { x: 8, y: 7 },
      { x: 9, y: 7 },
    ])
    expect(r.line).toHaveLength(3)
    expect([
      { x: 8, y: 4 },
      { x: 8, y: 8 },
    ]).toContainEqual(r.line[2])
  })

  it('renju 黑迴避禁手：同線雙四點是四四禁手 → 黑無 VCF；gomoku 黑則有', () => {
    // .X.X.X.X：補 x4 一子成同線兩個四（gomoku 雙威脅直接贏；renju 是四四禁手）。
    const diagram = `
      .X.X.X.X.......
      ...............
      ...............
      ...............
      ...............
      ...............
      ...............
      ...............
      ...............
      ...............
      ...............
      ...............
      ...............
      ...............
      O.O.O..........
    `
    const g = parseBoard(diagram)
    const rGomoku = solveVcf(g.board, BLACK, 'gomoku')
    expect(rGomoku.found).toBe(true)
    expect(rGomoku.line).toEqual([{ x: 4, y: 0 }])

    const r = parseBoard(diagram)
    const rRenju = solveVcf(r.board, BLACK, 'renju')
    expect(rRenju.found).toBe(false)
    expect(rRenju.truncated).toBe(false) // 是「證實無解」不是搜不完
  })

  it('白逼黑禁手：白衝四的唯一擋點是黑的三三禁手點 → 白勝', () => {
    // 白 (4..6,7) 衝四（左被黑 3,7 擋）；擋點 (8,7) 落黑會成
    // 直線 {(8,5)(8,6)} ＋斜線 {(9,8)(10,9)} 雙活三 → 黑禁手，擋不了。
    const { board } = parseBoard(`
      ...............
      ...............
      ...............
      ...............
      ...............
      ........X......
      ........X......
      ...XOOO........
      .........X.....
      ..........X....
    `)
    const r = solveVcf(board, WHITE, 'renju')
    expect(r.found).toBe(true)
    expect(r.line).toEqual([{ x: 7, y: 7 }])
  })

  it('對照組：擋點不是禁手 → 白這條衝四無以為繼，無 VCF', () => {
    const { board } = parseBoard(`
      ...............
      ...............
      ...............
      ...............
      ...............
      ........X......
      ........X......
      ...XOOO........
    `)
    const r = solveVcf(board, WHITE, 'renju')
    expect(r.found).toBe(false)
  })

  it('平靜局面無 VCF', () => {
    const { board } = parseBoard(`
      ...............
      ...............
      ...............
      ...............
      ...............
      ...............
      ...............
      .......X.......
      .......O.......
    `)
    expect(solveVcf(board, BLACK, 'renju').found).toBe(false)
    expect(solveVcf(board, WHITE, 'renju').found).toBe(false)
  })
})
