// 題庫判定器測試：每個案例的盤面以 ASCII 手工鋪設、期望值逐格推導。
// 注入同步版 solveVcf 當求解器（判定器介面允許同步/非同步兩用）。
import { describe, expect, it } from 'vitest'
import { parseBoard } from '../../engine/testutils.ts'
import { judgeAttackerMove, type VcfSolver } from '../judge.ts'
import { solveVcf } from '../../engine/vcf.ts'
import { BLACK, WHITE } from '../../engine/types.ts'

const solve: VcfSolver = (b, attacker, rule) =>
  solveVcf(b, attacker, rule, { maxDepth: 14, maxNodes: 500_000, timeLimitMs: 60_000 })

describe('judgeAttackerMove', () => {
  it('直接成五 → solved/five', async () => {
    // 黑 (4,7)(5,7)(6,7)(8,7)，跳四補中 (7,7) 成恰五。
    const { board } = parseBoard(`
      ...............
      ...............
      ...............
      ...............
      ...............
      ...............
      ...............
      ....XXX.X......
    `)
    const v = await judgeAttackerMove(board, BLACK, 'renju', { x: 7, y: 7 }, solve)
    expect(v).toEqual({ kind: 'solved', how: 'five' })
  })

  it('非衝四的一手 → wrong/not-four', async () => {
    const { board } = parseBoard(`
      ...............
      ...............
      ...............
      ...............
      ...............
      ...............
      ...............
      ....XXX........
    `)
    // (0,0) 離棋型遠，既不成五也不成四。
    const v = await judgeAttackerMove(board, BLACK, 'gomoku', { x: 0, y: 0 }, solve)
    expect(v).toEqual({ kind: 'wrong', reason: 'not-four' })
  })

  it('衝四且 VCF 仍在 → continue，守方回擋唯一成五點', async () => {
    // 黑斜線 (9,9)(10,10)(11,11)，白 (8,8) 擋一頭；另有黑橫排跳四
    // (4,7)(5,7)(6,7)(8,7)（成五點 (7,7)）當後續殺著。
    // 黑走 (12,12)：斜窗 (9..13) 4 黑 1 空 → 衝四，唯一成五點 (13,13)。
    // 守方擋 (13,13) 後黑仍可 (7,7) 直接成五 → VCF 仍在。
    const { board } = parseBoard(`
      ...............
      ...............
      ...............
      ...............
      ...............
      ...............
      ...............
      ....XXX.X......
      ........O......
      .........X.....
      ..........X....
      ...........X...
    `)
    const v = await judgeAttackerMove(board, BLACK, 'gomoku', { x: 12, y: 12 }, solve)
    expect(v).toEqual({ kind: 'continue', reply: { x: 13, y: 13 } })
  })

  it('衝四後 VCF 消失（已證實無解）→ wrong/loses-vcf', async () => {
    // 同上但拿掉橫排殺著：黑只有 (9,9)(10,10)(11,11)、白 (8,8)。
    // 黑走 (12,12) 衝四，守方擋 (13,13) 後黑再無任何四 → 無 VCF。
    const { board } = parseBoard(`
      ...............
      ...............
      ...............
      ...............
      ...............
      ...............
      ...............
      ...............
      ........O......
      .........X.....
      ..........X....
      ...........X...
    `)
    const v = await judgeAttackerMove(board, BLACK, 'gomoku', { x: 12, y: 12 }, solve)
    expect(v).toEqual({ kind: 'wrong', reason: 'loses-vcf' })
  })

  it('成四但守方已有成五點 → wrong/defender-five', async () => {
    // 白 (0,4)(0,5)(0,6)(0,7) 直排四（成五點 (0,3)/(0,8) 皆空）。
    // 黑走 (12,12) 衝四不解白棋 → 白直接成五，判錯。
    const { board } = parseBoard(`
      ...............
      ...............
      ...............
      ...............
      O..............
      O..............
      O..............
      O..............
      ........O......
      .........X.....
      ..........X....
      ...........X...
    `)
    const v = await judgeAttackerMove(board, BLACK, 'gomoku', { x: 12, y: 12 }, solve)
    expect(v).toEqual({ kind: 'wrong', reason: 'defender-five' })
  })

  it('renju 白衝四逼黑擋進禁手點 → solved/forced-forbidden', async () => {
    // 白斜線 (9,9)(10,10)(11,11)、黑 (12,12) 擋一頭。
    // 黑另有 (5,7)(6,7) 橫、(7,5)(7,6) 直——(7,7) 對黑是三三禁手點。
    // 白走 (8,8)：斜窗 (7,7)..(11,11) 4 白 1 空 → 衝四，唯一成五點 (7,7)。
    // 黑被迫擋 (7,7) 但那是黑的禁手點 → 擋不了，白勝。
    const { board } = parseBoard(`
      ...............
      ...............
      ...............
      ...............
      ...............
      .......X.......
      .......X.......
      .....XX........
      ...............
      .........O.....
      ..........O....
      ...........O...
      ............X..
    `)
    const v = await judgeAttackerMove(board, WHITE, 'renju', { x: 8, y: 8 }, solve)
    expect(v).toEqual({ kind: 'solved', how: 'forced-forbidden' })
  })

  it('renju 黑走禁手點 → wrong/forbidden', async () => {
    // (7,7) 是三三禁手（同上局面、無白棋威脅）。
    const { board } = parseBoard(`
      ...............
      ...............
      ...............
      ...............
      ...............
      .......X.......
      .......X.......
      .....XX........
    `)
    const v = await judgeAttackerMove(board, BLACK, 'renju', { x: 7, y: 7 }, solve)
    expect(v).toEqual({ kind: 'wrong', reason: 'forbidden' })
  })

  it('活四（兩個成五點）→ continue，守方擋一點、攻方下一手可成五', async () => {
    // 黑 (5,7)(6,7)(7,7)，兩端 (4,7)(8,7) 與更外側皆空。
    // 黑走 (8,7) 成活四（成五點 (4,7)/(9,7)）→ 守方擋一點，繼續。
    const { board } = parseBoard(`
      ...............
      ...............
      ...............
      ...............
      ...............
      ...............
      ...............
      .....XXX.......
    `)
    const v = await judgeAttackerMove(board, BLACK, 'gomoku', { x: 8, y: 7 }, solve)
    expect(v.kind).toBe('continue')
    if (v.kind === 'continue') {
      expect([
        { x: 4, y: 7 },
        { x: 9, y: 7 },
      ]).toContainEqual(v.reply)
    }
  })
})
